inherit_from: .rubocop_todo.yml

Metrics/LineLength:
  Max: 120

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
